import type { Metadata } from "next";
import { Golos_Text } from 'next/font/google'
import '@/styles/_base.sass'

const golos = Golos_Text({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-golos',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={golos.variable}>
      <body className={golos.className}>{children}</body>
    </html>
  );
}
